### ISSUE TITLE
READMEの内容確認

### ISSUE THREAD

**Issue by henami** [nims-dpfc/rdetoolkit#23]
READMEに書いてある内容について確認させてください。

1. 起動処理についての、import順

PEP8(https://pep8-ja.readthedocs.io/ja/latest/)とか見ていると
```
：
import文 は次の順番でグループ化すべきです:
1. 標準ライブラリ
2. サードパーティに関連するもの
3. ローカルな アプリケーション/ライブラリ に特有のもの
```
とあります。これからすると
```
from modules import process #独自で定義した構造化処理関数
import rdetoolkit
```
は、逆じゃないか? と思ったりするわけです。
```
import rdetoolkit
from modules import process #独自で定義した構造化処理関数
```

どうなんでしょ?

2. ローカル環境で動作させる場合の中のディレクトリ配置ですが、tasksupport内にもinvoice.jsonがありますが、これの意図するところはなんでしょう? data/invoice/invoice.jsonが使われるので、tasksupportに置く必要な無いと思います。

**Comment by henami** [comment]
さらにPEP8のページには
```
上のグループそれぞれの間には、1行空白を置くべきです。
```
とありますが、2行しかないので、その間に空白行置くのはやり過ぎな気はします。

**Comment by sonoh5n** [comment]
上記の件、ご指摘ありがとうございます！おっしゃる通りです。上記の内容を反映させたいと思います。

**Comment by sonoh5n** [comment]
適用したためClosedします。
