### ISSUE TITLE
RDEformatモードの例で、"custom_dataset_function=custom_dataset"を使用

### ISSUE THREAD

**Issue by henami** [nims-dpfc/rdetoolkit#38]
rdetoolkit/workflows.pyのrunメソッドには、以下のようなコメントが載っています。
````
：
        If options are specified (setting the mode to "RDEformat"):

        ```python
        ### main.py
        from rdetoolkit.config import Config
        from rdetoolkit import workflow
        from custom import custom_dataset # User-defined structuring processing function

        cfg = Config(extended_mode="rdeformat", save_raw=True, save_main_image=False, save_thumbnail_image=False, magic_variable=False)
        workflow.run(custom_dataset_function=custom_dataset, config=cfg) # Execute structuring process
        ```
````

"RDEFormatは、指定されたものをそのまま取り込むモードだと思っていましたが、custom.pyの"custom_dataset"関数に何を記述する想定でしょうか?

もし、記述しても無視されるのであれば、この部分を修正した方が間違いが少ないと思われます。

**Comment by henami** [comment]
@sonoh5n 試したところ

Config()中の"save_thumbnail_image=True"は有効ですね。False指定したら、もとのzipに含まれていても、thumbnailフォルダへのコピーはありませんでした。

**Comment by sonoh5n** [comment]
ご質問ありがとうございます。

> "RDEFormatは、指定されたものをそのまま取り込むモードだと思っていましたが、custom.pyの"custom_dataset"関数に何を記述する想定でしょうか?

`RDEFormat`は、指定のフォーマットであれば追加の構造化処理がなくても動作するモードです。そのため、基本的には、`custom_dataset_function=None`で問題ありません。

ユースケースとして、RDEFormatモードで登録したファイルに対して何か処理を実行したい場合、別途構築した構造化処理を実装できるようにしています。

**Comment by henami** [comment]
なるほど。

>RDEFormatモードで登録したファイルに対して何か処理を実行したい場合

ということは、先に登録処理(つまりコピー)が実行され、それに対して何かを実行するってことですね。

まぁそれをやるくらいなら、先にinputdataに置く方を直せばいいような。RDE登録日を格納する、みたいな使い方、かなー。

そうか! 設定では無効にしておいて、サムネイルの作成だけをやるってのもありだな。

> それでも、予めやっておくのが"RDEフォーマットモード"の良さ?のような気はするが……

ありがとうございました。
