### ISSUE TITLE
マルチファイルモードの拡張

### ISSUE THREAD

**Issue by hi-nagao** [nims-dpfc/rdetoolkit#46]
マルチファイルモードの処理において、現状はdividedフォルダを作成し、すべての処理が成功した場合に処理成功となっている。
これを、途中で失敗したデータがあっても、処理を継続し、失敗データのリストを出力するようなオプションを希望します。

**Comment by sonoh5n** [comment]
このissueでは、マルチファイルモードの処理失敗時のスキップ機能のみを実装するissueとします。

データセットの実行結果を返す処理は、別issueとして、切り出して対応する。https://github.com/nims-dpfc/rdetoolkit/issues/59

**Comment by sonoh5n** [comment]
また、複数登録モードは、Excelinvoiceもあるが、この機能は一旦マルチデータ登録のみとする。
