### ISSUE TITLE
ドキュメント整備：pipで表示される"Project description"の表現確認

### ISSUE THREAD

**Issue by henami** [nims-dpfc/rdetoolkit#58]
https://pypi.org/project/rdetoolkit/ で表示されるページですが

1) 起動処理についての部分で"from modules.modules import dataset#独自で定義した構造化処理関数"とあります。
もちろんこのままでも動きますが、コメントの#の前に1個空白が欲しいような気がします。

2) display_messsage(path)で、pathを単体で受けるように見えますが、srcpathsや、resource_pathsは、Pathのリストだかタプルだかのように見えますが、気にしなくてもいいですか? エラーが出ない時点で気にしなくてもいいのかもしれませんが。

3) RDE "2.0"っていう表現はありなんでしたっけ?

**Comment by sonoh5n** [comment]
コメントありがとうございます。

1. "from modules.modules import dataset#`は修正します。
2. 引数の命名規則を修正しておきます。
3. DICEのページの表記に合わせたいと思います。
