### ISSUE TITLE
invoice.schema.jsonのvaridationでexample要素が定義されているとエラーとなる

### ISSUE THREAD

**Issue by tosaka-nims** [nims-dpfc/rdetoolkit#64]
invoice.schema.jsonのvaridationでexample要素が定義されているとエラーとなりますが、テンプレート作成ツールではexampleを設定するとそれが出力されるようになっています。exampleの存在を許容するようにしていただけないでしょうか。

**Comment by sonoh5n** [comment]
ご報告ありがとうございます。確認します。

**Comment by sonoh5n** [comment]
@tosaka-nims 
`sample`がさす要素は、`(root).properties.custom.properties.exsamples`のことですね。再度確認します。

**Comment by sonoh5n** [comment]
こちら、`(root).properties.custom.properties.exsamples`の要素がarray型であればパスします。しかし、それ以外の型のデータが格納されていないか確認してみていただけますでしょうか。

**Comment by tosaka-nims** [comment]
失礼しました。invoice.schema.jsonを生成する側の不具合でした。本件は取り下げます。
