### ISSUE TITLE
nonshared_rawに格納されたファイルのpathを取得したい

### ISSUE THREAD

**Issue by ksasa-nims** [nims-dpfc/rdetoolkit#81]
rde2typesのRdeOutputResourcePathクラスのrawfiles変数は、rawフォルダに格納されたファイルすべてのパスをtupleとして保持しています。
これと同じように、nonshared_rawディレクトリに格納されたファイルすべてのパスをtupleとして保持した変数を作成してほしいです。

**Comment by sonoh5n** [comment]
> nonshared_rawディレクトリに格納されたファイルすべてのパスをtupleとして保持した変数を作成してほしいです。

`RdeOutputResourcePath.rawfiles`は、`raw`, `nonshared_raw`関係なく、`inputdata`ディレクトリに格納されたファイルを、タイルごとに解釈してtuple形式でデータを格納します。構造化処理を構築する際は、`raw`と`nonshared_raw`に関わらず、`RdeOutputResourcePath.rawfiles`にアクセスして入力データのパスを取得してください。

rawとnonshared_rawは、[inputdataの自動保存機能](https://nims-dpfc.github.io/rdetoolkit/latest/usage/config/config/)の保存先パスなので、rdeconfig.yamlで設定を記述してどちらに保存するか決定してください。

**Comment by sonoh5n** [comment]
上記の問題は、v1.0.2で解消ずみのためCloseします。
