### ISSUE TITLE
main.pyのimport文の下の空行

### ISSUE THREAD

**Issue by henami** [nims-dpfc/rdetoolkit#86]
たいした内容ではないんですが、一応書いておきます。

RDEToolKit1.0.2

init処理でできたmain.pyですが、"import rdetoolkit" と "rdetoolkit.workflows.run()"の間に、もう1行空の行があってもいいのかなと。いや、厳密にPEP8に従うなら、ですが。

考えすぎ、かしら?

**Comment by sonoh5n** [comment]
@henami ご指摘ありがとうございます。今回の指摘は、2行空けるということでしょうか。

```python
# The following script is a template for the source code.

import rdetoolkit


rdetoolkit.workflows.run()
```

現在、rdetoolkit v1.0.2では、以下のように生成されます。

```python
# The following script is a template for the source code.

import rdetoolkit

rdetoolkit.workflows.run()
```

**Comment by henami** [comment]
そうです。2行あけるべきなのかな、と思いまして。

**Comment by sonoh5n** [comment]
@henami 

返信できておらずすみません。上記の件、ここは1行空白で問題ないかなと思います。`トップレベルの関数とクラスの定義の間には2行の空行が必要`<https://peps.python.org/pep-0008/#blank-lines>で、import文と関数の間は、2行必要ないかそのような記述がPEP8に見当たりませんでした。

もし該当の文書やルールを探せていない可能性があるので、その場合は情報をいただけると嬉しいです。

**Comment by henami** [comment]
うーん確かに。

https://pep8-ja.readthedocs.io/ja/latest/#id11

こっちだな。すまんです。
