### ISSUE TITLE
CONTRIBUTING.md内の"GitLab 云々"

### ISSUE THREAD

**Issue by henami** [nims-dpfc/rdetoolkit#87]
https://github.com/nims-dpfc/rdetoolkit/blob/main/CONTRIBUTING.md
に
```
ドキュメントのコントリビュート

：
RDEToolKitのドキュメント

：
   ・ docstringは、各種モジュールの利用法が記載され、GitLab CI/CDで、自動ビルドされドキュメントが更新されます。
```
という感じで、こそっと"GitLab"があるわけですが、このGithubと、どこかにあるGitLabが連携している、ということでしょうか? それともGitHub CI/CDのTypo?

**Comment by sonoh5n** [comment]
これは誤りなので修正します。
