### ISSUE TITLE
main.py内でのコンフィグ設定方法の変更

### ISSUE THREAD

**Issue by henami** [nims-dpfc/rdetoolkit#89]
https://nims-dpfc.github.io/rdetoolkit/latest/rdetoolkit/workflows/#run

上記ドキュメントに、rdeconfig.y[a]mlファイルによらない、main.pyでの設定の仕方が記述されていますが、その通りにやっても反映されません。

設定に階層が設けられた為だと思われます。

なので
```
cfg = Config(save_raw=True, save_main_image=False, save_thumbnail_image=False, magic_variable=False)
```
は、例えば
```
cfg = Config()
cfg.system.save_raw = True
cfg.system.save_thumbnail_image = True
```
といった形で設定する必要があります。

* ちょっとどういう設定方法が正しいのかは、把握し切れていないですが……

新しい項目も増えていますので、上記ドキュメントのように全部記述するのがよいのかは微妙ですねー。

**Comment by henami** [comment]
```
cfg = Config()
cfg.system.save_raw = True
cfg.system.save_thumbnail_image = True
```
は中途半端、かな。
```
cfg = Config()
cfg.system.save_raw = True
cfg.system.save_nonshared_raw = False
cfg.system.save_thumbnail_image = True
```

rawへの書き込みを有効にしたら、nonshared_rawへの書き込みはオフにしないとな。

どっちも有効ってこと、あるのかしら?

**Comment by sonoh5n** [comment]
すみません、こちらはドキュメントを修正できていませんでした。

以下のように設定してください。

```python
from rdetoolkit.config import Config, MultiDataTileSettings, SystemSettings

config = Config(
    system=SystemSettings(extended_mode="MultiDataTile", save_raw=False, save_nonshared_raw=True, save_thumbnail_image=True),
    multidata_tile=MultiDataTileSettings(ignore_errors="False")
)

# 個別の設定を追加したい場合
config.mysetting = "Hello"
```

**Comment by henami** [comment]
config.mysettingに、dict()を指定して利用するのはありですか?

**Comment by henami** [comment]
もうしまったイシューだけど……

https://nims-dpfc.github.io/rdetoolkit/latest/usage/config/config/#_7

にある"custom"は、上のmysettingと同じようなもの、だな。つまりdict()は当然利用可能ってことだな。

* 上の例では、実装が必要ってのがわかりにくいかもしれん。それを書けばやってくれると思ってしまう人もいるかも。
